#!/bin/bash
#
echo -e "KARNA: Orphans? Well let's see.."
while [[ "$?" -eq "0"  ]]
do
    sudo pacman -Rs "$(pacman -Qdtq)"

    if [[ "$?" -ne "0" ]]
    then
        echo -e "There are no \"Orphans\" to remove :/"
    fi
    echo $?
done

