#!/bin/bash
#
export PATH_TO_VMS="$HOME/vms"
export TIME_DELAY=3
export SIZE_TO_INCREASE=10

echo -e "KARNA: I'm gonna shutdown the vm first."
sudo virsh shutdown "$1"
sleep "$TIME_DELAY"
cd "$PATH_TO_VMS" || exit
sudo qemu-img resize "$1".qcow2 "$SIZE_TO_INCREASE"
