#!/bin/bash
#
export PATH_TO_VMS="$HOME/vms"
export TIME_DELAY=3
export SIZE_TO_INCREASE=10

echo -e "KARNA: I'm gonna shutdown the vm first."
sudo virsh shutdown "$1"
sleep "$TIME_DELAY"
cd "$PATH_TO_VMS" || exit
echo -e "KARNA: now I'm resizing $1.qcow2 to $SIZE_TO_INCREASE GB"
sudo qemu-img resize "$1".qcow2 "$SIZE_TO_INCREASE"G
echo -e "KARNA: all done :*"
