#!/bin/bash
#
export QT_SCALE_FACTOR=1
# export QT_SCALE_FACTOR=1
# quassel &
# emacs &
# flameshot &
librewolf &
logseq &
anki &
# feedreader &
# telegram-desktop &
# signal-desktop &
# foliate &
# QT_SCALE_FACTOR=0.5
# okular &
