#!/bin/bash
#
echo -e "KARNA: Updating the keyring!"
sudo pacman -Sy archlinux-keyring

echo -e "KARNA: Populating keys!"
sudo pacman-key --populate archlinux

echo -e "KARNA: Refreshing keys."
sudo pacman-key --refresh-keys

echo -e "KARNA: Updating finally updating system!"
sudo pacman -Syu
echo -e "KARNA: updated!"

echo -e "KARNA: wanna update AUR packages too? (assuming yay is installed)"
yay -Syu
echo -e "KARNA: updated AUR!"

echo -e "KARNA: delete cache both from AUR and pacman?"
sudo pacman -Scc
yay -Sc
echo -e "KARNA: All done!"
